[[redirects]]
  from = "/docs/"
  to = "https://coderabbit.ai/docs/"
  force = true

[[redirects]]
  from = "/blog/"
  to = "https://coderabbit.ai/blog/"
  force = true

[[redirects]]
  from = "/blog1/"
  to = "https://coderabbit.ai/blog/"
  force = true
  status = 200
